// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuklvplhccvnvvqqbqtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1a2x2cGxoY2N2bnZ2cXFicXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTg5NjgsImV4cCI6MjA3MjI3NDk2OH0.DWYNkUvx0Uma2RkXEWCnMHauYJRkMA1A8TEYw0_p6_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});